spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Student_Internship_Portal?createDatabaseIfNotExist=true
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret: Z2VuZXJhdGVhLXJlc2VjdXJlLWxvbmdlci1rZXktd2l0aC0zMmJ5dGVz
  expiration: 86400000